BEGIN;

ALTER TABLE dogs
	ADD COLUMN IF NOT EXISTS expectation TEXT NOT NULL DEFAULT '';

ALTER TABLE dogs
	ALTER COLUMN expectation TYPE TEXT;

ALTER TABLE user_profiles
	ADD COLUMN IF NOT EXISTS prior_training_topic_ids BIGINT[] NOT NULL DEFAULT '{}'::BIGINT[];

ALTER TABLE user_profiles
	ADD COLUMN IF NOT EXISTS training_goal_topic_ids BIGINT[] NOT NULL DEFAULT '{}'::BIGINT[];

COMMIT;
