-- 결제 없이 이용권을 부여하는 프로모션 코드(promotion/domain/PromotionCode)와 그 사용 기록(PromotionCodeRedemption).
-- 코드는 운영 SQL로 직접 넣으므로 대문자로 정규화된 값만 받는다.
-- 혜택 기간은 사용 시각부터의 ISO-8601 기간(access_period, 예: P3M)과 고정 종료 시각(access_ends_at) 중 하나만 둔다.
-- redeemable_until은 코드 입력 기한, max_redemptions는 전체 사용 수 상한이며 NULL이면 제한이 없다.
CREATE TABLE "promotion_codes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(50) NOT NULL UNIQUE CHECK ("code" = UPPER(TRIM("code"))),
    "access_period" VARCHAR(20),
    "access_ends_at" TIMESTAMPTZ,
    "redeemable_until" TIMESTAMPTZ,
    "max_redemptions" INTEGER CHECK ("max_redemptions" > 0),
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    CHECK (("access_period" IS NULL) <> ("access_ends_at" IS NULL))
);

-- 코드 하나가 부여하는 이용권 종류. 모든 이용권을 여는 코드는 네 종류 모두를 가진다.
CREATE TABLE "promotion_code_entitlement_types" (
    "promotion_code_id" BIGINT NOT NULL REFERENCES "promotion_codes" ("id"),
    "entitlement_type" VARCHAR(50) NOT NULL,
    UNIQUE ("promotion_code_id", "entitlement_type")
);

-- 한 행이 한 사용자의 코드 사용 한 번이다. 같은 코드는 사용자당 한 번만 쓴다.
-- access_ends_at은 사용 시각에 계산한 혜택 종료 시각으로, 이후 코드 설정이 바뀌어도 유지된다.
CREATE TABLE "promotion_code_redemptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "promotion_code_id" BIGINT NOT NULL REFERENCES "promotion_codes" ("id"),
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "access_ends_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    CONSTRAINT "uk_promotion_code_redemptions_promotion_code_id_user_id" UNIQUE ("promotion_code_id", "user_id")
);
