-- 현재 JPA 엔티티(src/main/java/**/domain/*.java) 기준 초기 스키마.
-- 이후 엔티티 변경은 반드시 새 V{n} 마이그레이션으로 반영한다 (dev/prod는 ddl-auto가 스키마를 만들지 않는다).

CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "user_profiles" (
    "user_id" BIGINT PRIMARY KEY REFERENCES "users" ("id"),
    "nickname" VARCHAR(50) NOT NULL,
    "profile_image_url" VARCHAR(512) NOT NULL,
    "birth_date" DATE,
    "mbti" VARCHAR(4) NOT NULL,
    "gender" VARCHAR(10) NOT NULL,
    "prior_training_topic_ids" BIGINT[] NOT NULL,
    "training_goal_topic_ids" BIGINT[] NOT NULL,
    "is_completed_tooltip" BOOLEAN NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "local_accounts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL UNIQUE REFERENCES "users" ("id"),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "social_accounts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "provider" VARCHAR(20) NOT NULL,
    "provider_id" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255),
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    UNIQUE ("provider", "provider_id")
);

-- user 모듈 소속이라 user_id를 ID로만 참조하고 FK를 걸지 않는다 (모듈 경계)
CREATE TABLE "dogs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "breed" VARCHAR(30) NOT NULL,
    "sex" VARCHAR(10) NOT NULL,
    "birth_date" DATE,
    "weight_kg" NUMERIC(5, 2) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "profile_image_url" VARCHAR(512) NOT NULL,
    "expectation" TEXT NOT NULL,
    "deleted_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "dog_personalities" (
    "dog_id" BIGINT NOT NULL REFERENCES "dogs" ("id"),
    "personality" VARCHAR(30) NOT NULL,
    UNIQUE ("dog_id", "personality")
);

CREATE TABLE "ai_reports" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "video_object_key" VARCHAR(512) NOT NULL,
    "title" VARCHAR(200),
    "content" TEXT,
    "status" VARCHAR(30) NOT NULL,
    "upload_expires_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL
);

CREATE TABLE "user_lesson_progress" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "lesson_id" BIGINT NOT NULL,
    "completed_count" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    UNIQUE ("user_id", "lesson_id")
);

CREATE TABLE "user_selected_topic" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL UNIQUE,
    "topic_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "training_categories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "icon_url" VARCHAR(512) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "topics" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "training_category_id" BIGINT NOT NULL REFERENCES "training_categories" ("id"),
    "title" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "detail" TEXT NOT NULL,
    "icon_url" VARCHAR(512) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "curriculums" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic_id" BIGINT NOT NULL REFERENCES "topics" ("id"),
    "title" VARCHAR(200) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "thumbnail_url" VARCHAR(512) NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "lessons" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "curriculum_id" BIGINT NOT NULL REFERENCES "curriculums" ("id"),
    "title" VARCHAR(200) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "estimated_minutes" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "cards" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "lesson_id" BIGINT NOT NULL REFERENCES "lessons" ("id"),
    "title" VARCHAR(200) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "instruction" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

-- 그래프 순환을 막기 위해 next_card_id는 엔티티에서도 ID로만 참조한다 (JPA 연관관계·FK 없음)
CREATE TABLE "card_branches" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "card_id" BIGINT NOT NULL REFERENCES "cards" ("id"),
    "next_card_id" BIGINT,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "card_media" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "card_id" BIGINT NOT NULL REFERENCES "cards" ("id"),
    "media_type" VARCHAR(20) NOT NULL,
    "url" VARCHAR(512) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);
