-- 리프레시 토큰 발급 이력(user/domain/RefreshToken). token_id는 JWT jti(UUID 문자열 36자)이며 재발급 조회 키라 유니크.
CREATE TABLE "refresh_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "token_id" VARCHAR(36) NOT NULL UNIQUE,
    "expires_at" TIMESTAMP NOT NULL,
    "revoked_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);
