-- 리프레시 토큰 발급 이력 (user/domain/RefreshToken.java).
-- 토큰 원문 대신 JWT jti(token_id)를 저장하고, 무효화된 토큰은 행을 지우지 않고 revoked_at으로 표시한다.
CREATE TABLE "refresh_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "token_id" VARCHAR(36) NOT NULL UNIQUE,
    "expires_at" TIMESTAMP NOT NULL,
    "revoked_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);
