-- JMeter INSERT 부하 측정용 임시 테이블(loadtest/domain/LoadTestRecord). user 모듈 소속 user_id는 ID로만 참조하고 FK를 걸지 않는다 (모듈 경계)
CREATE TABLE "load_test_records" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL
);
