-- RevenueCat 웹훅으로 기록하는 스토어 구매(payment/domain/Purchase)와 그로 얻은 권한(payment/domain/Entitlement).
-- product_id·store·identifier는 RevenueCat이 정의하는 값이라 enum 대신 웹훅 값 원본을 문자열로 저장한다.
-- 시각 컬럼은 Instant라 Hibernate 매핑에 맞춰 TIMESTAMPTZ로 둔다. 바뀌는 값이 환불·회수 시각뿐이라 updated_at은 두지 않는다.

-- 한 행이 한 거래라 transaction_id(스토어 거래 ID)가 유니크다.
-- price는 결제 통화 기준 가격이며 스토어가 알려 주지 않으면 price·currency가 null이다.
CREATE TABLE "purchases" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "transaction_id" VARCHAR(100) NOT NULL UNIQUE,
    "product_id" VARCHAR(100) NOT NULL,
    "store" VARCHAR(30) NOT NULL,
    "price" NUMERIC(19, 4),
    "currency" VARCHAR(3),
    "purchased_at" TIMESTAMPTZ NOT NULL,
    "refunded_at" TIMESTAMPTZ,
    "created_at" TIMESTAMP NOT NULL
);

-- 결제 이력을 회원별로 구매 시각 순으로 조회한다. 엔티티 @Index와 이름·컬럼을 맞춘다.
CREATE INDEX "idx_purchases_user_id_purchased_at" ON "purchases" ("user_id", "purchased_at");

-- 한 행이 RevenueCat entitlement 하나라 통합 상품 구매는 여러 행이 된다. 같은 구매로 같은 권한을 두 번 주지 않는다.
-- user_id는 purchases에서도 알 수 있지만, 권한 확인을 구매와 조인하지 않고 하도록 둔다.
CREATE TABLE "entitlements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "purchase_id" BIGINT NOT NULL REFERENCES "purchases" ("id"),
    "identifier" VARCHAR(50) NOT NULL,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMP NOT NULL,
    UNIQUE ("purchase_id", "identifier")
);

-- 회원이 특정 권한을 가졌는지 확인한다. 엔티티 @Index와 이름·컬럼을 맞춘다.
CREATE INDEX "idx_entitlements_user_id_identifier" ON "entitlements" ("user_id", "identifier");
