-- 스토어 구매 한 건과 그로 얻은 이용권(payment/domain/Entitlement). RevenueCat 웹훅으로 부여·회수된다.
-- 한 행이 한 거래라 transaction_id(스토어 거래 ID)가 유니크이고, 어느 시기를 열어 주는지는 product_id로 코드에서 계산한다.
-- price는 결제 통화 기준 가격이며 스토어가 알려 주지 않으면 price·currency가 null이다.
-- purchased_at·revoked_at은 Instant라 Hibernate 매핑에 맞춰 TIMESTAMPTZ로 둔다. 바뀌는 값이 회수 시각뿐이라 updated_at은 두지 않는다.
CREATE TABLE "entitlements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "transaction_id" VARCHAR(100) NOT NULL UNIQUE,
    "product_id" VARCHAR(30) NOT NULL,
    "store" VARCHAR(20) NOT NULL,
    "price" NUMERIC(19, 4),
    "currency" VARCHAR(3),
    "purchased_at" TIMESTAMPTZ NOT NULL,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMP NOT NULL
);

CREATE INDEX "idx_entitlements_user_id" ON "entitlements" ("user_id");
