-- 시기별 이용권(payment/domain/Entitlement). RevenueCat 웹훅으로 부여·회수되며 시기 하나당 한 행이다.
-- granted_at·revoked_at은 Instant라 Hibernate 매핑에 맞춰 TIMESTAMPTZ로 둔다.
CREATE TABLE "entitlements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "life_stage" VARCHAR(20) NOT NULL,
    "product_id" VARCHAR(30) NOT NULL,
    "store" VARCHAR(20) NOT NULL,
    "granted_at" TIMESTAMPTZ NOT NULL,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE INDEX "idx_entitlements_user_id" ON "entitlements" ("user_id");
