-- 댓글 대상과 작성자는 다른 모듈의 엔티티라 FK 없이 종류와 ID 값으로만 참조한다. root_id는 스레드의 최상위 댓글, parent_id는 실제로 답한 댓글이다
CREATE TABLE "comments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "target_type" VARCHAR(20) NOT NULL,
    "target_id" BIGINT NOT NULL,
    "author_id" BIGINT NOT NULL,
    "root_id" BIGINT REFERENCES "comments" ("id"),
    "parent_id" BIGINT REFERENCES "comments" ("id"),
    "content" VARCHAR(500) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE INDEX "idx_comments_target_type_target_id_id" ON "comments" ("target_type", "target_id", "id");
CREATE INDEX "idx_comments_root_id_id" ON "comments" ("root_id", "id");

CREATE TABLE "comment_likes" (
    "comment_id" BIGINT NOT NULL REFERENCES "comments" ("id"),
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("comment_id", "user_id")
);
