-- 시기별 이용권(payment/domain/Entitlement). RevenueCat 웹훅으로 부여·회수되며 시기 하나당 한 행이다.
-- transaction_id는 스토어 거래 ID로, 통합 이용권은 한 거래로 시기마다 행이 생기므로 (거래, 시기)가 유니크.
-- purchased_at·revoked_at은 Instant라 Hibernate 매핑에 맞춰 TIMESTAMPTZ로 둔다. 바뀌는 값이 회수 시각뿐이라 updated_at은 두지 않는다.
CREATE TABLE "entitlements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("id"),
    "transaction_id" VARCHAR(100) NOT NULL,
    "life_stage" VARCHAR(20) NOT NULL,
    "product_id" VARCHAR(30) NOT NULL,
    "store" VARCHAR(20) NOT NULL,
    "purchased_at" TIMESTAMPTZ NOT NULL,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMP NOT NULL,
    UNIQUE ("transaction_id", "life_stage")
);

CREATE INDEX "idx_entitlements_user_id" ON "entitlements" ("user_id");
