-- 카드·작성자는 다른 모듈의 엔티티라 FK 없이 ID로만 참조한다. parent_id는 답글이 속한 최상위 댓글이다
CREATE TABLE "card_comments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "card_id" BIGINT NOT NULL,
    "author_id" BIGINT NOT NULL,
    "parent_id" BIGINT REFERENCES "card_comments" ("id"),
    "content" VARCHAR(500) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE INDEX "idx_card_comments_card_id_id" ON "card_comments" ("card_id", "id");
CREATE INDEX "idx_card_comments_parent_id_id" ON "card_comments" ("parent_id", "id");

CREATE TABLE "card_comment_likes" (
    "comment_id" BIGINT NOT NULL REFERENCES "card_comments" ("id"),
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("comment_id", "user_id")
);
